lib/FCM1/Cm.pm

The `/intertrac/` syntax does not appear to work any more. Use
`/search?q=` syntax instead.
Close #86.

fcm bdi --trac: fix using alternate syntax

---

lib/FCM1/Cm.pm
t/fcm-branch-delete/00-simple.t
t/fcm-branch-delete/01-bad-arg.t

Previously, if a bad argument is specified while in a working copy, it
will continue to use the working copy URL.

fcm branch-delete: fail if bad arg specified

---

t/fcm-merge/00-simple.t
t/fcm-merge/01-complex.t
t/fcm-merge/test_header

This adds some `svn mergeinfo` and `svn:mergeinfo` tests to `fcm merge`.
This helps document current behaviour for #69.
@matthewrmshin, please review.

fcm merge: add mergeinfo tests

---

lib/FCM1/Cm.pm
t/fcm-commit/04-externals.t
t/fcm-commit/test_header

`svn status` contains empty lines if the working copy has an external
item.

fcm ci: fix Perl warning on empty status lines

---

lib/FCM/System/Make/Build/Task/ExtractInterface.pm
t/fcm-make/02-build-ext-iface/expected/t1.interface
t/fcm-make/02-build-ext-iface/src/t1.f90

Arguments to Fortran `EXTERNAL` statements were being matched in
case-sensitive mode. This change fixes the problem.
Fix #175.

fcm make: build: fix external case in ext-iface

---

lib/FCM/System/Make.pm
t/fcm-make/10-log.t

Absolute path makes it harder to relocate the directory.

fcm make: .fcm-make/log symlink should be relative

---

doc/user_guide/command_ref.html
lib/FCM/CLI/fcm-make.pod

The command changes directory to PATH before doing anything.

fcm make: fix --directory=PATH documentation

---

lib/FCM/System/Make/Build.pm
lib/FCM/Util/Locator/FS.pm
t/fcm-make/39-build-source-with-dot.t
t/fcm-make/40-extract-fs-source-with-dot.t

This allows users to specify a source file path name with a leading dot
in the directory.
Fix #180.

source file find: ignore hidden only if under $ns

---

lib/FCM/System/Make/Build.pm
lib/FCM/System/Make/Extract.pm
lib/FCM/System/Make/Share/Dest.pm
t/fcm-make/45-dest-mv.t

If an old make context's `dest` setting does not agree with the location of where it is loaded, the loader will attempt to update any relevant path related settings that are paths under the old `dest` setting.
Fix #185.

fcm make: load previous ctx: support relocate

---

doc/user_guide/annex_cfg.html
doc/user_guide/command_ref.html
doc/user_guide/make.html
lib/FCM/CLI/Parser.pm
lib/FCM/CLI/fcm-make.pod
lib/FCM/System/Make/Build.pm
lib/FCM/System/Make/Extract.pm
t/fcm-make/46-archive-mode.t

If archive mode is specified, TAR-GZIP these items by default:
* `.fcm-make/cache/extract/`
* `build/include/`
* `build/o/`
The archive-OK categories for the sub-directories under `build/` are configurable.
Related to #185, #189 and metomi/rose#1621.
@benfitzpatrick please review. This should be the final piece of the puzzle.

fcm make: new --archive option

---

lib/FCM/CLI/Parser.pm
lib/FCM1/Cm.pm

Always use:
`--config-option config:working-copy:exclusive-locking-clients=`
with:
`--diff-cmd fcm_graphic_diff`
Close #179.

fcm (b)diff -g: don't lock client

---

sbin/post-commit-bg
sbin/pre-commit
t/svn-hooks/02-pre-commit.t
t/svn-hooks/03-post-commit-bg.t

pre-commit: log (but don't email) >1MB transactions
post-commit: report pre-commit size threshold (normally 10MB) for any >1MB changesets

pre/post commit: improve changeset size diagnostic

---

doc/user_guide/annex_cfg.html
doc/user_guide/make.html
lib/FCM/System/Make/Build.pm
lib/FCM/System/Make/Preprocess.pm
t/fcm-make/47-build-target-modifier-ns.t
t/fcm-make/47-build-target-modifier-ns/fcm-make.cfg
t/fcm-make/47-build-target-modifier-ns/src/greet/greet.f90
t/fcm-make/47-build-target-modifier-ns/src/greet/world.nl
t/fcm-make/47-build-target-modifier-ns/src/hello/hello.f90
t/fcm-make/47-build-target-modifier-ns/src/hello/world.nl

The `category` modifier should now work.
The `ns` modifier never worked, and is removed.
Instead `task` and `category` selection can now be filtered by
name space.
Close #194.

fcm make: build: fix target select modifier

---

CONTRIBUTING.md
doc/user_guide/command_ref.html
lib/FCM/CLI/Parser.pm
lib/FCM/CLI/fcm-branch-create.pod

@matthewrmshin when you get a minute would you mind taking a look at this? Given that people are now creating branches-of-branches fairly often typing --branch-of-branch every time seems a little excessive (do we even need this option now, surely it should be the default if the user runs "fcm branch-create" with a branch as the source?).
I'm also not sure how best to test this, if I just set $FCM_HOME to be my git branch I can't seem to run branch-create at all, any thoughts on what I should be doing to test this?

Allow bob as a synonym of branch-of-branch

---

doc/user_guide/annex_cfg.html
doc/user_guide/make.html
doc/user_guide/overview.html
lib/FCM/Context/Make/Build.pm
lib/FCM/System/Make/Build.pm
lib/FCM/Util.pm
t/fcm-make/48-build-sha1.t
t/fcm-make/48-build-sha1/fcm-make.cfg
t/fcm-make/48-build-sha1/src/hello.f90

MD5 or one of SHA algorithms in Digest::SHA.

fcm make: build: flexible checksum method

---

lib/FCM/System/Make/Build/FileType/C.pm
t/fcm-make/49-build-c-more.t
t/fcm-make/49-build-c-more/fcm-make.cfg
t/fcm-make/49-build-c-more/src/greet.c
t/fcm-make/49-build-c-more/src/hello.c
t/fcm-make/49-build-c-more/src/hi.c

Now recognise `void main(` and just `main(`.` Close #203.

fcm make: build: more main pattern for C sources

---

doc/user_guide/annex_cfg.html
doc/user_guide/make.html
lib/FCM/System/Make/Build.pm
t/fcm-make/50-build-target-dep.t
t/fcm-make/50-build-target-dep/fcm-make.cfg
t/fcm-make/50-build-target-dep/src/greet.f90
t/fcm-make/50-build-target-dep/src/greet_world.f90
t/fcm-make/51-build-target-no-dep.t
t/fcm-make/51-build-target-no-dep/fcm-make.cfg
t/fcm-make/51-build-target-no-dep/src/greet.f90
t/fcm-make/51-build-target-no-dep/src/greet_mod.f90
t/fcm-make/51-build-target-no-dep/src/greet_world.f90
t/fcm-make/51-build-target-no-dep/src2/hello_mod.f90

Support syntax such as (where `hello.exe` is a target name instead of the namespace of a source):
```cfg
build.prop{dep.o}[hello.exe]=world.o greet.o
```
Close #67.

fcm make: build: support more prop on target

---

lib/FCM/System/Make/Extract.pm
t/fcm-make/53-extract-conflict-incr.t

On conflict, the target status was recorded incorrectly as unchanged.
This caused incremental extract to succeed in error. This change fixes
the problem.
@benfitzpatrick @scwhitehouse please review.

fcm make: extract: fix target status on conflict

---

lib/FCM/Util/ConfigReader.pm
t/fcm-cfg-print/00-env.t
t/fcm-cfg-print/test_header

A (environment) variable value of 0 is previously lost on substituion.
This fixes the problem.
@benfitzpatrick @scwhitehouse please review.

cfg: fix variable substitution of value 0

---

CONTRIBUTING.md
lib/FCM/System/Make/Share/Dest.pm

This fixes #226 in the NCI environment.

Pass a file handle rather than a path to gunzip to work around problems

---

doc/user_guide/getting_started.html
lib/FCM/System/CM/CommitMessage.pm

This removes `gedit` from the editor documentation, as (at our site's version) the command can return before the file is saved and the editor is actually closed.

Remove gedit from editor documentation

---

lib/FCM/Admin/System.pm

Use default temporary directory instead of destination directory as
temporary work area.

admin backup: fix temporary work location

---

lib/FCM/System/Make/Share/Dest.pm

Redundant argument in `sprintf` at `lib/FCM/System/Make/Share/Dest.pm` line 273.
The warning shows up on my Ubuntu 16.04 LTS VM. (The format variable supplied to `sprintf`can sometimes be a null string.)

Fix Perl sprintf warning

---

lib/FCM/Admin/System.pm

Follow on from #230, to ensure that TMPDIR is used in preference to PWD.

admin backup: more on temporary work location

---

.travis.yml
README.md
t/fcm-make/00-build-basic.t
t/fcm-make/05-build-c-cxx-basic.t
t/fcm-make/12-build-class-prop.t
t/fcm-make/23-build-omp.t
t/fcm-make/41-ctx-name.t
t/fcm-make/42-make-mirror-make2.t
t/fcm-make/43-ctx-name-inherit.t
t/fcm-make/44-ctx-name-inherit-compat.t
t/fcm-make/46-archive-mode.t
t/svn-hooks/03-post-commit-bg.t

Run `fcm test-battery` on Travis CI. For some reason, the sort order on the Travis CI box is very different. I have also added some extra polling to ensure the stability of  `t/svn-hooks/03-post-commit-bg.t`.

Integrate with Travis CI

---

.travis.yml
lib/FCM/Admin/System.pm
t/fcm-add-trac-env/00-basic.t
t/svn-hooks/03-post-commit-bg.t

Both `admin` and `owner` are set up to have `TRAC_ADMIN` permissions,
but this allows us to distinguish between the admin team who set up
hosting of the Trac environments and the owners of the software
projects.
Install Trac on Travis CI build, so we can have CI for Trac related functionality.

fcm-add-trac-env: add `owner` permission

---

lib/FCM/System/Make/Share/Dest.pm

Use `TMPDIR` where possible for temporary files on load/dump of `ctx.gz`.
Apparently, `IO::File->new_tmpfile()` uses `/tmp` regardless of whether `TMPDIR` is defined in the environment.
@scwhitehouse @paulcresswell please review.

fcm make: use TMPDIR on load/dump ctx.gz

---

lib/FCM/System/Make/Build.pm
t/fcm-make/54-build-ignore-missing-dep-ns.t
t/fcm-make/54-build-ignore-missing-dep-ns/fcm-make.cfg
t/fcm-make/54-build-ignore-missing-dep-ns/src/greet.f90
t/fcm-make/54-build-ignore-missing-dep-ns/src/greet_mod.f90
t/fcm-make/54-build-ignore-missing-dep-ns/src/greet_world.f90
t/fcm-make/54-build-ignore-missing-dep-ns/src2/hello_mod.f90

Logic was incorrect and untested.
The old logic would fail like this:
```
[FAIL] Not an ARRAY reference at /opt/fcm/bin/../lib/FCM/System/Make/Build.pm line 1310.
```
Bug reported by @gdcarver via email.

Fix fcm make: build.prop{ignore-missing-dep-ns}

---

lib/FCM1/CmBranch.pm
lib/FCM1/CmUrl.pm
t/fcm-add-trac-env/00-basic.t
t/fcm-branch-delete/02-rosie.t
t/lib/bash/svn_test_header

`fcm branch-delete` was producing Perl undefined variable warning messages on branches of suites in Rosie repositories, due to the fact that it is unable to determine the branch owner using the branch URL. This change fixes the warning message.
@scwhitehouse @paulcresswell please review.

branch-delete: fix Perl warning on rosie branches

---

lib/FCM1/Cm.pm

This happened on an unexpected usage. A user has checked out an entire
project tree, and then run `fcm switch trunk` on it. Clearly it did not
work, but the added Perl warning was not helpful either.
@scwhitehouse Please review. I don't think we need a 2nd reviewer for this.

fcm switch: fix Perl warning

---

doc/user_guide/annex_cfg.html
lib/FCM/System/Make/Build/Task/Link.pm
t/fcm-make/01-build-link-opts.t

Revert default behaviour to create temporary dependent object library before linking it to executable. (This effectively reverts #245 - as the changed behaviour has raised unforeseen side effects.)
New build property to suppress this.

fcm make build prop: link-without-ar

---

lib/FCM/System/Make/Build/FileType/Fortran.pm
t/fcm-make/55-build-fortran-prog-unit-tail-comment.t
t/fcm-make/55-build-fortran-prog-unit-tail-comment/fcm-make.cfg
t/fcm-make/55-build-fortran-prog-unit-tail-comment/src/greet.f90
t/fcm-make/55-build-fortran-prog-unit-tail-comment/src/greet_mod.f90

Fortran dependency analysis was not handling tail comment of a program unit correctly.
Fix #252.

fcm make: build: handle program unit tail comment

---

.travis.yml
lib/FCM/System/Make/Build.pm
lib/FCM/System/Make/Build/FileType/Fortran.pm
t/fcm-make/56-build-fortran-submodule.t
t/fcm-make/56-build-fortran-submodule/fcm-make.cfg
t/fcm-make/56-build-fortran-submodule/src/class_impl.f90
t/fcm-make/56-build-fortran-submodule/src/class_mod.f90
t/fcm-make/56-build-fortran-submodule/src/simple_impl.f90
t/fcm-make/56-build-fortran-submodule/src/simple_mod.f90
t/fcm-make/56-build-fortran-submodule/src/test.f90

Fix #255.
Complete with test for building Fortran code with submodules, borrowed from fab.
Note on building a Fortran submodule.
* The source file containing the submodule has a compile time dependency on the `*.mod` of the parent module. (This is already handled in the logic, the the current regular expression is a bit flawed.)
* The source file containing the parent module has a link time dependency on the `*.o` file containing the submodule. (This is handled by the new *reverse dependency* logic.)
Note on Travis CI:
* Upgrade to use Ubuntu 16.04 xenial, latest distro available on Travis CI.
* Need to install `gfortran-9` separately (for Fortran 2008+) features, and wrap it so the `gfortran` command executes `gfortran-9`.
* Install Subversion normally, which should be good enough on …

fcm make build: correctly support Fortran submodule

---

lib/FCM/Admin/System.pm
t/fcm-add-trac-env/00-basic.t

We are no longer able to add version control repository at initenv time.
This change calls a separate `trac-admin . repository add ...` to do this.

Trac 1.2 trac-admin . initenv args change

---

CONTRIBUTING.md
lib/FCM/System/Make/Build/FileType/Fortran.pm

Add fix for module regexp. Add a space to regexp so that it doesn't incorrectly ignore modules that begin with function/subroutine

Add space to fortran module regexp

---

sbin/post-commit-bg
sbin/trac_hook

Also fix a bug in `sbin/trac_hook` which only becomes apparent if `$FCM_SVN_HOOK_COMMIT_DUMP_DIR` is not set in `sbin/post-commit-bg` (otherwise the variable `$NAME` is defined)

sbin/post-commit-bg: allow threshold for size warning to be configurable

---

lib/FCM/Admin/System.pm
t/fcm-add-trac-env/00-basic.t

#258 changed the behaviour of `fcm-add-trac-env` to add a named repository rather than the default - this PR reproduces the old behaviour.

fcm-add-trac-env: Setup the default repository rather than a named one

---

.github/workflows/tests.yaml
sbin/svnperms.py
t/fcm-make/23-build-omp.t
t/lib/bash/test_header

Add Ubuntu 20.04.
Treat Subversion version 1.10 and above the same.
Use python2 in place of python in tests and in svnperms.py.
Replace the use of "yes" (to avoid warning messages) following this advice:
https://superuser.com/questions/86340/linux-command-to-repeat-a-string-n-times
Prevent other jobs being cancelled if one fails:
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
Checkout all history (git describe fails without this):
https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches

Simplify github actions test environments
